[tool.poetry]
name = "python-template"
version = "0.1.1"
description = "Python template for various projects."
authors = ["Arisu W. <arisuchr@riseup.net>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
wemake-python-styleguide = "^0.16.1"
pylint = "^2.14.5"
#portray = "^1.7.0"
#pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
